user:
  name:
    maximum_length: 50
  email:
    maximum_length: 255
  password:
    minimum_length: 6
  address:
    maximum_length: 255

paginate:
  user_perpage: 50

checkbox:
  true: "1"

picture:
  maximun_size: 5
  accepted_file: "image/jpeg,image/gif,image/png"
